services:
    pgvector:
        image: 'pgvector/pgvector:pg16'
        environment:
            - 'POSTGRES_DB=template'
            - 'POSTGRES_PASSWORD=password'
            - 'POSTGRES_USER=user'
        labels:
            - "org.springframework.boot.service-connection=postgres"
        ports:
            - '5432:5432'
    redis:
        image: 'redis:latest'
        ports:
            - '6379:6379'